### ISSUE TITLE
Trying to add Rollback feature on this module

### ISSUE THREAD

**Issue by spark-green** [jonom/silverstripe-version-history#11]
Hi guys,

First of all I am sorry this is not an issue on module, but i am trying to extend this module and it is giving me lot of trouble. And couldn't find better place to ask my query.

 I am trying to add an extra button on history tab "Rollback to this version" see below image and when user clicks on this button it will rollback to that version to live. Same as how you rollback page history.

![image](https://user-images.githubusercontent.com/2790964/45397366-096e6180-b683-11e8-9f5b-8c37baed398c.png)

I am trying to us doRollbackTo method on DataObject as below, but it is not working.
`$this->owner->doRollbackTo('Live')`

Has anyone tried extending this module to use rollback feature ?  If yes, can you please share some ideas? Ta.

**Comment by jonom** [comment]
Hi @spark-green you might get more help on the [forum](https://forum.silverstripe.org/). I think if you upgrade to SS4 though, this functionality is built in.
